[tools]
"cargo:cargo-expand" = "latest"
"cargo:cargo-nextest" = "latest"
"cargo:pep257" = "latest"
"cargo:timeout-cli" = "latest"
editorconfig-checker = "latest"
ephemeral-postgres = "latest"
osv-scanner = "latest"
rust = "stable"
typos = "latest"
